from ConfigMenu import *
from Credits import *
from Dead import *
from Gameplay import *
from Help import *
from Menu import *
from Pause import *
from Ranking import *
from StartGame import *
