from ConfigMenu import *
from Credits import *
from Dead import *
from GamePlayTest import *
from Help import *
from Main import *
from Menu import *
from Pause import *
from Ranking import *
from StartGame import *
from TextFieldTest import *
