from Beholder import *
from Bomb import *
from Bone import *
from Boomerang import *
from Boss import *
from Cage import *
from Chest import *
from Cyclone import *
from Dog import *
from Door import *
from Dummy import *
from Golem import *
from HalfMoon import *
from Neighbour import *
from Orb import *
from Player import *
from Skeleton import *
from Slime import *
from Sparkle import *
from Spike import *
