from Beholder import *
from Bomb import *
from Boomerang import *
from Chest import *
from Door import *
from Golem import *
from Orb import *
from Player import *
from Skeleton import *
from Slime import *
from Spike import *
